wallpaper {
    monitor = eDP-1
    path = /home/Toby/.config/hypr/wallpaper/mklgustafsson-small-memory.png
    fit_mode = cover
}

wallpaper {
    monitor = *
    path = /home/Toby/.config/hypr/wallpaper/mklgustafsson-small-memory.png
    fit_mode = cover
}

ipc = on
splash = false
