wallpaper {
    monitor = eDP-1
    path = /home/Toby/Pictures/kvacm-falling-sun.png
    fit_mode = cover
}

wallpaper {
    monitor = *
    path = /home/Toby/Pictures/kvacm-falling-sun.png
    fit_mode = cover
}

ipc = on
splash = false
